### PR TITLE
strings sorted, edited and added

### PR DESCRIPTION
**Pull request by Henry2o1o**

### CODE REVIEW

**Comment by neobuddy89** [comment]
@gwolf2u strings are wrong. dont merge.

**Comment by gwolf2u** [comment]
I only validated xml 
thought all good

**Comment by neobuddy89** [comment]
there is no plurals xml , he added plurals.xml too

**Comment by gwolf2u** [comment]
that doesn't invalidate as far as I know

**Comment by gwolf2u** [comment]
we used that in crDroid settings if I recall even if main strings xml didn't include it

**Comment by gwolf2u** [comment]
reverted 
use strings from trans branch if you want to update

**Pull request merged**
